table Industry
	lineageTag: ae151e7b-1add-4d98-8e55-27b5d609039b

	column ID
		dataType: int64
		isHidden
		isKey
		keepUniqueRows
		lineageTag: 207c4cc0-e27a-44b2-926a-00edc536fec4
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Industry
		dataType: string
		keepUniqueRows
		lineageTag: 0acc7caf-a564-4783-aa06-e5ef46a0556f
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Image
		dataType: binary
		lineageTag: 777d9b8c-441b-46d3-8fb4-4d619c54fe25
		dataCategory: Image
		isDefaultImage
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Industry = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT [dbo].[Industry].*   FROM [dbo].[Industry]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"ID", "ID"}, {"Industry", "Industry"}, {"Image", "Image"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"ID", Int64.Type}, {"Industry", type text}, {"Image", type binary}})
				in
				    #"Changed Type"

